AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'talon-engine

  Talon Engine Serverless Application

  '
Globals:
  Function:
    Timeout: 300
Resources:
  UrlDownloadRequestFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: jenkimrdevbucket
        S3Key: 51d4355195cd63f544993d37c2c4951c
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      Role: UrlDownloadRequestFunctionIamRole
      Timeout: 900
      Environment:
        Variables:
          S3_BUCKET_NAME: talon-content-downloads
          MYSQL_HOST: mariadb
          MYSQL_USERNAME: talon
          MYSQL_PASSWORD: talon
          MYSQL_DB_NAME: talon
Outputs:
  UrlDownloadRequestFunction:
    Description: Downloads URL requests sent to it via SQS and saves contents to S3
    Value:
      Fn::GetAtt:
      - UrlDownloadRequestFunction
      - Arn
  UrlDownloadRequestFunctionIamRole:
    Description: Implicit IAM Role created for URL Download Request function
    Value:
      Fn::GetAtt:
      - UrlDownloadRequestFunction
      - Arn
  StartScheduledRequestFunction:
    Description: Passes event triggered json on to the url downloader SQS
    Value:
      Fn::GetAtt:
      - StartScheduledRequestFunction
      - Arn
  StartScheduledRequestFunctionIamRole:
    Description: Implicit IAM Role created for Starting a Scheduled Request function
    Value:
      Fn::GetAtt:
      - StartScheduledRequestFunction
      - Arn
