AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    talon-engine

    Talon Engine Serverless Application

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 300


Resources:

    UrlDownloadRequestFunction:
        Type: AWS::Lambda::Function
        Properties:
            Code: url_download_request/
            Handler: lambda_function.lambda_handler
            Runtime: python3.7
            Role: UrlDownloadRequestFunctionIamRole
            Timeout: 900
            Environment:
                Variables:
                    S3_BUCKET_NAME: talon-content-downloads
                    MYSQL_HOST: mariadb
                    MYSQL_USERNAME: talon
                    MYSQL_PASSWORD: talon
                    MYSQL_DB_NAME: talon

    GlobalThreatLevel:
        Type: AWS::Lambda::Function
        Properties:
            Code: global_threat_level/
            Handler: lambda_function.lambda_handler
            Runtime: python3.7
            Timeout: 900

    RssFeed:
        Type: AWS::Lambda::Function
        Properties:
            Code: rssFeed/
            Handler: lambda_function.lambda_handler
            Runtime: python3.7
            Timeout: 900

Outputs:
    UrlDownloadRequestFunction:
      Description: "Downloads URL requests sent to it via SQS and saves contents to S3"
      Value: !GetAtt UrlDownloadRequestFunction.Arn

    UrlDownloadRequestFunctionIamRole:
      Description: "Implicit IAM Role created for URL Download Request function"
      Value: !GetAtt UrlDownloadRequestFunction.Arn

    StartScheduledRequestFunction:
      Description: "Passes event triggered json on to the url downloader SQS"
      Value: !GetAtt StartScheduledRequestFunction.Arn

    StartScheduledRequestFunctionIamRole:
      Description: "Implicit IAM Role created for Starting a Scheduled Request function"
      Value: !GetAtt StartScheduledRequestFunction.Arn

    GlobalThreatLevel:
      Description: "Gets the global threat level from SANS"
        Value: !GetAtt GlobalThreatLevel.Arn
